version: '3'

services: 
  
  decks-backend:
    image: decks_backend
    build: .
    container_name: decks-container
    depends_on: 
      - mongodb
    expose:
      - 3000
    networks:
      - decks-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - decks-network

  proxy-service:
    image: nginx:mainline-alpine
    container_name: reverse_proxy_server_container
    depends_on:
      - decks-backend
    ports: 
      - 80:80
    volumes: 
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - decks-network
    command: [nginx, '-g', 'daemon off;']

    
volumes:
  data:

networks:
  decks-network:
    driver: bridge