version: '3'

services: 
  
  decks-backend:
    image: decks_backend
    build: .
    container_name: decks-container
    depends_on: 
      - mongodb
    expose:
      - 3000
    networks:
      - decks-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - decks-network

  proxy-service:
    image: nginx:mainline-alpine
    container_name: reverse_proxy_server_container
    depends_on:
      - decks-backend
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx-conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./dhparam:/etc/ssl/certs
    networks:
      - decks-network
    command: [nginx, '-g', 'daemon off;']

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - proxy-service
    command: certonly --webroot --webroot-path=/var/www/certbot --email aallehyany@gmail.com --agree-tos --no-eff-email --force-renewal -d decks-builder.com

    
volumes:
  data:
  certbot-etc:
  certbot-var:

networks:
  decks-network:
    driver: bridge
